---
title: "Study of US Craft Beer and Breweries"
author: "David Stroud, Cory Thigpen, Korey MacVittie, and Stacy Conant"
date: "February 2018"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)
```


```{r}
library(ggplot2) # Data visualization
library(readr) # CSV file I/O, e.g. the read_csv function
library(dplyr) # Heavy use of this library
```

```{r}
# Read in beer and breweries data set
Beers <- read.csv('Beers.csv')
Breweries <- read.csv('Breweries.csv')
```


```{r}
# Renamed Brewery_id to Brew_ID to satisfy merging requirement
Beers <- rename(Beers, Brew_ID = Brewery_id)
```

```{r}
# 2. Merge beer data with the breweries data.
BrewPub <- full_join(Beers, Breweries, by="Brew_ID")
#(dplyr::tbl_df(BrewPub))
```

```{r}
# 1.How many breweries are present in each state?
table(Breweries$State)
```


```{r}
# 2.a Print the first six observations
print(head(BrewPub))
```


```{r}
# 2. b Print the last six observations
print (tail(BrewPub))
```

```{r}
# 3. Report the number of NA's in each column.
MissingValues <- sapply(BrewPub, function(x)sum(is.na(x)))
print(MissingValues)
```

```{r}
# 4. Compute the median alcohol content unit for each state.
Bitter <- BrewPub %>%
  na.omit() %>%
group_by(State) %>%
summarise(Median = median(ABV)) %>%
arrange(Median)
#dplyr::tbl_df(Bitter) ~ duplicated next line
Bitter %>% tbl_df %>% print(n=50)
```

```{r}
# 4. a Compute the median alcohol content unit for each state.
FireWater <- BrewPub %>%
  na.omit() %>%
group_by(State) %>%
summarise(Median = median(IBU)) %>%
arrange(Median)
# dplyr::tbl_df(FireWater) duplicated next line
FireWater %>% tbl_df %>% print(n=50)
```

```{r}
# 4. b Plot a bar chart to compare IBU by state 
ggplot(data=FireWater, aes(x=State, y=Median)) +
  geom_bar(stat="identity", fill="steelblue")+
  theme_minimal() +
  theme(axis.text.x=element_text(size=rel(0.8), angle=90)) +
  ggtitle("Median IBU by State") +
  labs(x="State",y="IBU")
```

```{r}
# 4. c Plot a bar chart to compare ABV by state
ggplot(data=Bitter, aes(x=State, y=Median)) +
  geom_bar(stat="identity", fill="steelblue")+
  theme_minimal() +
  theme(axis.text.x=element_text(size=rel(0.8), angle=90))+
  ggtitle("Median ABV by State") +
  labs(x="State",y="ABV")
```

```{r}
# 5. Which state has the maximum alcoholic (ABV) beer?
print(BrewPub[which.max(BrewPub$ABV),])
```

```{r}
# 5. a Which state has the most bitter (IBU) beer?
print(BrewPub[which.max(BrewPub$IBU),])
```

```{r}
# Summary for ABV variable
summary(BrewPub$ABV)
```


```{r}
# Combine Bitterness of Beer and Alcohol Content df for ease of analysis
BitterFire <- full_join(FireWater, Bitter, by="State")
# dplyr::tbl_df(BitterFire)
```

```{r}
# Change column names to reflect meaningful variable name
BitterFire$Median.x <- (BitterFire$Median.x)
#dplyr::tbl_df(BitterFire)
```

```{r}
# 7. Draw a scatter plot to compare relationship between beer 
# bitterness and alcohol content
ggplot(BrewPub, aes(x=IBU, y= ABV)) +
  geom_point(shape=1) +
   geom_smooth(method=lm) + # add linear regression line
  theme(axis.text.x=element_text(size=rel(1.0)))+
ggtitle("Correlation between IBU and ABV ") +
  labs(x="IBU",y="ABV")
```



